version: 2.1

jobs:
  hello-job:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
       - add_ssh_keys:
          fingerprints:
            - "b9:be:44:71:f2:c5:8a:86:11:af:7a:e0:19:14:4b:1e"

workflows:
  my-workflow:
    jobs:
      - hello-job
